name: pileet-blink
version: master
summary:  Blink snap for the Raspberry Pi with Gobot
description: |
  This is a simple example to blink an LED in the Raspberry Pi
  using the Gobot framework.

confinement: devmode

apps:
  pileet-blink:
    command: pileet-blink

parts:
  pileet-blink:
    source: .
    plugin: go
    go-importpath: github.com/gabeduke/pileet-blink

